### ISSUE TITLE
Avoid os.exit()

### ISSUE THREAD

**Issue by johnd0e** [pkulchenko/MobDebug#19]
There are several places in mobdebug.lua where os.exit() called (on error, or debug session end).
I need somehow avoid this in order to continue normal client execution.

**Comment by pkulchenko** [comment]
@johnd0e, yes, but this is not likely to change. There is DONE command that doesn't trigger `os.exit()` (it's available as `Project | Detach` command in ZeroBrane Studio) and some environments set `os.exit` to `require('mobdebug').done`.

**Comment by johnd0e** [comment]
> (it's available as Project | Detach command in ZeroBrane Studio)
It is grayed:
![image](https://cloud.githubusercontent.com/assets/1838643/8035807/30d3ea34-0dfc-11e5-9603-ffaa7e8eaf43.png)
But it gets available afer I press Shift-F9.
Isn't it strange?

**Comment by pkulchenko** [comment]
It's by design as the current DONE interface requires the debugger to be suspended to be executed properly. It may be possible to execute it while the debugger is running, but it requires changes in both the debugger and the IDE. Would it resolve the issue if it was available all the time?

**Comment by johnd0e** [comment]
>Would it resolve the issue if it was available all the time?
Well, it is currently hidden too deep in menu (and has no keyboard shortcut).
I would prefer to have dedicated toolbar button (and some way to remove "Stop" button).

**Comment by pkulchenko** [comment]
> Well, it is currently hidden too deep in menu (and has no keyboard shortcut).

Yes, but you can assign it a shortcut

> I would prefer some config option to replace "Stop" button action.

You can hide the Stop button and/or change the icon on the Detach button to use the stop button

> Or maybe dedicated toolbar button for detach (and some way to remove "Stop" button).

It should be there already; it's on the right side of the Stop button.

You can hide the Stop button with `toolbar.icons[ID.STOPDEBUG] = false`.

**Comment by johnd0e** [comment]
> Yes, but you can assign it a shortcut

Cool!
But I am unable to find ID of the action (other actions is in `keymap.lua` but not this one)


>It should be there already; it's on the right side of the Stop button.

Indeed!
(I was confused by difference between menu command name and hint text)

**Comment by pkulchenko** [comment]
> But I am unable to find ID of the action (other actions is in keymap.lua but not this one)

@johnd0e, indeed; I pushed a change that fixed that. The ID is `ID.DETACHDEBUG`. You can also check `toolbar.lua` for the list of all toolbar icons. It's possible to enable/disable/add/change buttons/icons/descriptions from the config file.

**Comment by johnd0e** [comment]
Thanks.

Concerning issue subject: there are several places where `os.exit` is called in case of error.
And on next line after I see `os.exit` `return <somevalues>`.
How is it supposed to be used?

I guess to return from function I need first to reassign `os.exit` to dummy function, right?

And when those errors can happen?
Is it possible to into them using mobdebug in client application?

**Comment by pkulchenko** [comment]
> I guess to return from function I need first to reassign os.exit to dummy function, right?

Yes; that's precisely why the `return` is there (as `os.exit` may not exit the app if overwritten).

> And when those errors can happen?
> Is it possible to run into them using mobdebug in client application?

Yes, the debugging will be aborted in this case, but it should be properly handled by both the debugger and the controller (in the IDE).

**Comment by johnd0e** [comment]
> Yes, the debugging will be aborted in this case

Actually not just debugging be aborted, but whole client application will be aborted (unless it reassigns os.exit).
And this necessity of `os.exit` overloading seems non-obvious (and even non-natural, sort of hack) for me, especially given that such subtle details are not documented anywhere.

That's what this issue about.
My suggestion is to include this to mobdebug interface.
e.g.:
```
mobdebug.on_exit = os.exit
```
Imho, with this addition things get simpler, easy to document, and conventional to override.

**Comment by pkulchenko** [comment]
I'm slowly getting around on this. Having `mobdebug.onexit` and using it instead of using `os.exit` directly seems like a good idea.
