### ISSUE TITLE
How can i debug a process with ZeroBrane Studio with MobDebug?

### ISSUE THREAD

**Issue by xzzh999** [pkulchenko/MobDebug#21]
Hi, bigcow, i am a newbie to lua, and can you tell me hao to debug with another windows process with
ZeroBrane Studio? I used some kind of lua debug ide like LuaStdio before(cracked version and unstable,in my country this is a very common habit), and i knew it inject into the process and so to debug it. Now i don't want to use LuaStdio, i use ZeroBrane Studio with MobDebug, and it's a great tool. 

In common work, ZeroBrane Studio debug is very comfortable, but when i want debug some windows process which written in C++ with lua vm, i don't know hao to start. I already knows how to remote debug a script, but how to this with an another process? please help me, 3Q very much!

**Comment by pkulchenko** [comment]
You should be able to debug any Lua process; you can check the [instructions for remote debugging](http://studio.zerobrane.com/doc-remote-debugging).

If you want to ask a question, there are several way listed on the [community page](http://studio.zerobrane.com/community).

**Comment by xzzh999** [comment]
Thank you very much, i install LuaSocket and MobDebug and now i can remote debug the process now. but there still a question:   when the script had an error or assert at the runtime, can MobDebug  pointed out that which line and in which script file that had happened? ( I found ZeroBrane Studio had nothing information in the output window)

**Comment by xzzh999** [comment]
I found lua_pcall had a errfunc parameter to put in, this can used to print the stack.

**Comment by pkulchenko** [comment]
>  when the script had an error or assert at the runtime, can MobDebug pointed out that which line and in which script file that had happened? ( I found ZeroBrane Studio had nothing information in the output window)

You can wrap your call into a `xpcall` and use `debug.traceback` to print the stack trace, but it needs to be done in your script as when you start debugging with the `start()` call, there is no way to intercept the error at the Lua level. Lua 5.1 used to support `debug.traceback` overwrite, but it's not supported in Lua 5.2 and 5.3 (and probably not in LuaJIT either).

**Comment by xzzh999** [comment]
Well, you are exactly right.
