### ISSUE TITLE
package.loaded.mobdebug = mobdebug

### ISSUE THREAD

**Issue by johnd0e** [pkulchenko/MobDebug#23]
```
-- this is needed to make "require 'modebug'" to work when mobdebug
-- module is loaded manually
package.loaded.mobdebug = mobdebug
```
I see mobdebug now does not `require` itself in code, so this line is probably not needed anymore.

**Comment by pkulchenko** [comment]
This is for those (rare) cases when mobdebug is included in the code and not as a standalone file (for the ease of packaging). You code, which you may not want to modify, can still use `require "mobdebug"` and even though there is no `mobdebug.lua` file, it will still work.

**Comment by johnd0e** [comment]
> You code, which you may not want to modify

If I include the whole module in my code then it is very easy to modify `package.loaded` myself.
(though as for me, I would prefer to avoid such bad practice anyway)

**Comment by pkulchenko** [comment]
This is not necessarily a bad practice. I've seen (mobile) environments that don't allow for external modules, so "require" fails if the file is not in "loaded".

Still, this is a good point; I'll make the change.

**Comment by johnd0e** [comment]
> This is not necessarily a bad practice.

Agree.
I object only against modifying of `loaded` inside of module itself.


> I've seen (mobile) environments that don't allow for external modules

It still should be possible to access mobdebug via some global variable.
