### ISSUE TITLE
Debugger connection closed after some commands

### ISSUE THREAD

**Issue by mpeterv** [pkulchenko/MobDebug#24]
Using the version from the master branch (by the way, it would be great to have 0.62 available through Luarocks), the debugger exits without any errors after running any of `exec`, `listw`, `listb` and `help`. On the side of the program being debugged I get

```
lua: test.lua: Debugger connection closed
stack traceback:
	[C]: in function 'error'
	./mobdebug.lua:665: in function <./mobdebug.lua:505>
	test.lua:5: in main chunk
	[C]: ?
```

**Comment by ianfitzpatrick** [comment]
Just a "me too" on this one. I'm just starting out trying out learning Lua for use with Love2D and ran into this problem as well.

As soon as I type `help` I get a list of help commands, and then dumped back to the mac command line.

**Comment by ianfitzpatrick** [comment]
FWIW, commit `cb0bb5bb80a0562ec5aed0f44bddccd47a809d0c` does not seem to have this issue. Help command works fine and doesn't dump me to command line.

**Comment by pkulchenko** [comment]
@ianfitzpatrick, are you saying that cb0bb5bb doesn't have that issue, but the HEAD does? The last two commits shouldn't make any difference as one updated the tests and one fixed the localization in the code.

**Comment by ianfitzpatrick** [comment]
@pkulchenko Yep, sorry, this is exactly what I'm telling you :( !

**Comment by mpeterv** [comment]
cb0bb5b also has the issue for me.

**Comment by pkulchenko** [comment]
Yes, I suspect that it's an earlier commit, but I haven't tracked it down yet.

**Comment by mpeterv** [comment]
I bisected and it's 94026b2.

**Comment by mpeterv** [comment]
Specifically, in 94026b2 debugging stops when `handle()` returns nil values, but some commands return nil or nothing on success, including `help`: https://github.com/pkulchenko/MobDebug/blob/94026b286b1a81919fcf9a33af7c74ccdcf8544a/src/mobdebug.lua#L1550

**Comment by pkulchenko** [comment]
@mpeterv, @ianfitzpatrick, should be fixed now (assuming you use the `listen` function from the module). Thank you for the report and the details.
