### ISSUE TITLE
update luarocks version

### ISSUE THREAD

**Issue by simonwu-os** [pkulchenko/MobDebug#25]
can you update luarocks version please?
In rocks, the MobDebug version is 0.55. It is too old and can't be used in Lua5.3.

**Comment by pkulchenko** [comment]
@simonwu-os, I'll try, but another user has ownership of mobdebug on luarocks website. I asked for a transfer, but it may take some time.

**Comment by pkulchenko** [comment]
I've released v0.63 and pushed to luarocks: http://luarocks.org/modules/paulclinger/mobdebug. Let me know if you find any issues with that version.
