### ISSUE TITLE
"Run To Cursor" and "Continue" don't work when remote debugging.

### ISSUE THREAD

**Issue by chansey97** [pkulchenko/MobDebug#30]
After read the documents (https://studio.zerobrane.com/doc-remote-debugging), I try to debug my project using remote debugging.

After run my application, I could see green arrow pointing to the next statement after the start() call in ZeroBrane Studio and I can press "Step over" to jump code step by step. 

The problem is :
I only jump code step by step. If I toggle breakpoint at the next 3 line and press "Continue" or press  "Run To Cursor" at  the next 3 line in my code, the code fly....

This issue will not be reproduced when using local debugging. (anything is OK in local debugging)
operating system: windows7
IDE version: ZeroBraneStudio 1.30
Thanks.

**Comment by pkulchenko** [comment]
Take a look at [this FAQ answer](https://studio.zerobrane.com/doc-faq#why-breakpoints-are-not-triggered) to see if any of this applies to you. If none of this helps, I'll need a small example that you can reproduce this on.

Also, there have been several small improvements in working with relative paths in remove debugger, so you may try with v1.40 that was just made available.

**Comment by chansey97** [comment]
@pkulchenko 
I wrote a small example which can reproduce this issue.
Unzip the test.zip. 

There 3 folder and 1 batch file.
bin,lualibs: Don't worry, all of these files are copied from your ZeroBraneStudio code. (no virus)
src: main.lua is the main program.
test.bat: I wrote a batch file which can launch this application.

reproduce step:
1. Open ZeroBrane Studio. Go to Project | Start Debugger Server and start the debugger server
2. Open main.lua.
3. click test.bat
4. You should see a green arrow pointing to the next statement after the start() call in ZeroBrane Studio.
5. set breakpoint at 'line 10'
6. press F5
7. the code fly.....
[test.zip](https://github.com/pkulchenko/MobDebug/files/440180/test.zip)

**Comment by pkulchenko** [comment]
What do you set the project directory to and what's the content of the Output window? I think it's a matter of setting the project directory to the correct location.

**Comment by chansey97** [comment]
1. the project directory is "open main.lua and press 'set project directory from current file' button'".
2. Output window: I capture a screenshot.
![untitled](https://cloud.githubusercontent.com/assets/4015056/18026008/3baf1692-6c6d-11e6-816a-4471731f6ff7.png)

You can use my small example (test.zip) to reproduce this issue by your self.

**Comment by pkulchenko** [comment]
You can inconsistent paths in your scripts: `e:/work/test/src/main.lua` where the breakpoint is set doesn't match `e:/work/test//src/main.lua` path reported by the interpreter. Try starting using `lua.exe %~dp0src\main.lua`. The debugger does do some normalization of paths, but only if it finds up-dir references (`../`).

**Comment by chansey97** [comment]
Thanks.
It works well when using lua.exe %~dp0src\main.lua.
But I think it will be better if ZBS can filter "//"to '/' when source mapping.

**Comment by pkulchenko** [comment]
ok; thanks for confirming it's working. I'll consider having additional processing, but there are some valid reasons not to do it in this case.
