### ISSUE TITLE
overwriting debug.traceback corrupts the lua global environment

### ISSUE THREAD

**Issue by LinkerJL** [pkulchenko/MobDebug#31]
I tried to integrate MobDebug into Cocos2d-x lua in my game.
But I found that MobDebug overwrites the **debug.traceback** function.
Both Cocos2d-x (v3.10) and my code use **debug.traceback** (see `cocos2d/functions.lua` for example). This causes conflicts.
Change behavior of a common function is not a best practice, I think. 
Why not just provide another function (i.e. **mob.traceback**)?

**Comment by pkulchenko** [comment]
@LinkerJL, what version of Lua interpreter are you using? `debug.traceback` is used to provide a limited way to debug after run-time errors, but it's effective only in Lua 5.1 and can be skipped with other versions.

Also, there is a simple workaround: save the value of `debug.traceback` before `start()` call of the debugger and restore it after the call.

**Comment by LinkerJL** [comment]
@pkulchenko, sorry for responding late.
Yes, I use Lua 5.1.

I have tried your workaround and it works. Thanks a lot. 
And I think you should document about this.

**Comment by pkulchenko** [comment]
> And I think you should document about this.

Good point. Where would you check for this information? I'm thinking about adding this to README, but not sure if that's where the users would check...

**Comment by pkulchenko** [comment]
@LinkerJL, btw, what was the original problem? The function that overwrites `debug.traceback` returns the "original" value by `debug.traceback`, so you should get the correct result.

**Comment by LinkerJL** [comment]
@pkulchenko, sorry for responding late again.

Let me explain the original problem:
`cocos2d/functions.lua` has some hard code as follow

```
    local traceback = string.split(debug.traceback("", 2), "\n")
    print("dump from: " .. string.trim(traceback[3]))
```

and MobDedug just erase part of the content return by debug.traceback

```
return (dtraceback(...):gsub("(stack traceback:\n)[^\n]*\n", "%1"))
```

So the conflict occurs.

**Comment by LinkerJL** [comment]
Usually, I would look for this information in README. 
It would be better if you add a section after the **Dependencies** section. Users could skip it if they were in a hurry, or they could read it for help if they found a problem.
