### ISSUE TITLE
Can't debug scripts running on mobile devices

### ISSUE THREAD

**Issue by leiradel** [pkulchenko/MobDebug#34]
The path to scripts in mobile applications are different from the one in my development machine. Worse, it changes on each build at least on iOS devices.

I tried to add a command to MobDebug to specify a regex pattern to transform local file paths in the mobile devices into paths that ZeroBrane Studio could find in the development's machine file system, but failed to make it work.

It would be nice if remote debugging of scripts running on remote machines with different file paths was supported. I can give it another try with some guidance on how to implement it properly.

**Comment by pkulchenko** [comment]
@leiradel, when you say debugging doesn't work, do you mean that the breakpoints are not working or do you mean it's not working completely (you can't start debugging for some reason)?

This type of debugging should definitely be supported, although in complex situations it may require a bit of help from the user. Mobdebug not only supports cross-platform debugging, but it also provides debugging of mismatched paths on the application and the controller/IDE sides and will try to match the fragments of those paths to find a proper base directory to set.

In most cases it's sufficient to set the project directory to the directory that matches the one in the application; for example, in your development setup you may have `/foo/bar/project/subdir/file.lua` and in your application you may have `/very/different/path/project/subdir/file.lua` and if you set the project directory to `/foo/bar/project`, the IDE (ZeroBrane Studio) will figure out the mapping and all the debugging features should work.

You will get a message `Mapped remote request for ... to ...`, which will indicate the mapping that the IDE could find based on the project directory and the path that was reported from the applications. If the breakpoints are still not working, you may want to check [this section in the FAQ](https://studio.zerobrane.com/doc-faq#why-breakpoints-are-not-triggered) and include the content of the Output window when you start debugging.

**Comment by leiradel** [comment]
I'll double check and reopen this if I can't make it work. Thanks for answering, and sorry for the noise.

**Comment by pkulchenko** [comment]
@leiradel, definitely re-open if it doesn't work for you; it's quite possible you have some configuration that requires setting base directory; see [this thread](https://www.freelists.org/post/zerobrane/Remote-debugging-IDE-project-path-vs-actual-file-path) for related discussion.

**Comment by leiradel** [comment]
Hi, I've made some tests and still have issues. I'm testing a Mac build running on the same machine as the debugger. All scripts are in the same folder.

When I debug using ZeroBrane, it stops at the beginning of the script and I can run it step by step, but I can't step into functions defined in other Lua modules. If I use the command-line debugger, everything works fine.

One thing that strikes me as odd is that the command-line debugger shows filenames in lowercase, i.e. `Paused at file /users/.../contents/documents/testscripts/test_1.lua line 11` (the ellipsis are for the sake of brevity), but the path and the actual Lua files have mixed case. ZeroBrane in opened with `TestScripts` as its project.

Maybe that's why ZeroBrane can't find them? Is it an issue with MobDebug, or maybe I'm passing the wrong names when calling the Lua C API to run scripts? I find it strange that ZeroBrane can find `test_1.lua` which already uses mixed case in the path: `/Users/.../Contents/Documents/TestScripts/test_1.lua`. However, the other scripts also have mixed case, maybe it's only the file name that confuses ZeroBrane?

Thanks in advance.

**Comment by pkulchenko** [comment]
> I can't step into functions defined in other Lua modules.

This depends on whether the file is already open in the IDE or not. By default the debugger will not step into functions defined in files not open in the IDE, so the solution is to either open the files or to set `editor.autoactivate=true` (see https://studio.zerobrane.com/doc-editor-preferences).

> Maybe never taking the case into account would be better?

That's a tricky one, because on case-insensitive systems opening "Test.lua" and "TEST.lua" will open the same file (with the Lua interpreter reporting names as opened), but setting breakpoints on Test.lua when the interpreter reports TEST.lua won't work, so there is some additional logic to take that into account. It get's more complicated with cross-platform debugging when the controller and the application have different settings, but it should still work as you'd expect it (or at least I'm not aware of any issues caused by the case conversion).

Note that the stepping into files is not affected by this conversion in any way, only breakpoints would be affected.

Also note that the reporting of the names may indeed be slightly different for the auto-opened files; there was a recent fixed applied for old versions of Windows (#744), but I'm not aware of similar problems on OSX (and Linux shouldn't be affected).

**Comment by pkulchenko** [comment]
> Paused at file /users/.../contents/documents/testscripts/test_1.lua line 11 (the ellipsis are for the sake of brevity), but the path and the actual Lua files have mixed case. ZeroBrane in opened with TestScripts as its project.

I just re-read the message and can say that I wouldn't expect the lower-casing to happen here, although there are configurations of iOS and MacOS that are case insensitive. Currently the logic for the case-preserving check is the following:

```lua
local win = os and os.getenv and (os.getenv('WINDIR') or (os.getenv('OS') or ''):match('[Ww]indows')) and true or false
local mac = not win and (os and os.getenv and os.getenv('DYLD_LIBRARY_PATH') or not io.open("/proc")) and true or false
local iscasepreserving = win or (mac and io.open('/library') ~= nil)
```

Is `iscasepreserving` value `true` in your case? This would explain why the names are lowercase, but shouldn't stop the IDE from finding and opening the files. I'll doublecheck the logic, but as far as I remember, it should work.

**Comment by leiradel** [comment]
> set `editor.autoactivate=true`

Ah, thanks, this is so useful it should be on by default.

> That's a tricky one, because on case-insensitive systems opening "Test.lua" and "TEST.lua" will open the same file

Yes, things are working just fine so there's no reason to change anything. I only thought it could be the reason for the problems I was facing.

> Is iscasepreserving value true in your case?

I'm having trouble getting the value straight out of `mobdebug.lua`, but I ran those lines in a OS X prompt:

```lua
local win = os and os.getenv and (os.getenv('WINDIR') or (os.getenv('OS') or ''):match('[Ww]indows')) and true or false
local mac = not win and (os and os.getenv and os.getenv('DYLD_LIBRARY_PATH') or not io.open("/proc")) and true or false
local iscasepreserving = win or (mac and io.open('/library') ~= nil)

print(win)
print(mac)
print(iscasepreserving)
```

```sh
$ lua test.lua
false
true
true
```

So I'm also puzzled by the case conversion.

Another thing is, my scripts live in different folders for the sake of organization, but are copied to one same folder during the build. The result is that I have to keep a folder with all my Lua scripts in sync with the real source folder to be able to debug them, otherwise the paths won't match.

Of course this is an issue of my workflow and not with MobDebug or ZeroBrane, but maybe there could be a debugger command to rewrite file paths? I could provide a regex, or (even better) a function, that would be applied to all paths before reporting them, so they could be adjusted to match my folder organization.

I'm not sure how many others would benefit from this though.

Cheers
