### ISSUE TITLE
Version 0.70 not available via LuaRocks

### ISSUE THREAD

**Issue by komapa** [pkulchenko/MobDebug#36]
Just as the title says: 

```
bash-4.1# luarocks install mobdebug 0.70

Error: No results matching query were found.
```

**Comment by pkulchenko** [comment]
You can install it locally as the spec is provided in `misc/mobdebug-0.70-1.rockspec`. I'll push it to luarocks.

**Comment by pkulchenko** [comment]
@komapa, uploaded the spec: http://luarocks.org/modules/paulclinger/mobdebug/0.70-1. Can you check the install and update the ticket?
