### ISSUE TITLE
调试请教-how debug

### ISSUE THREAD

**Issue by ygm521** [pkulchenko/MobDebug#44]
您好！
我想Windows上使用IDEA远程调试Linux上的openresty的lua程序。
widow上IntelliJ IDEA 2018.2.1+EmmyLua 1.2.6-IDEA182
Linux上程序test.lua中加入了： 
   local mobdebug = require("src.initial.mobdebug");
  mobdebug.start(8172);

但是我不清楚Linux是作为服务端监听8172，Windows上使用idea作为客户端连接Linux的8172端口？原理是怎样的？如何使用呢？谢谢！

Hello!
I want to use IDEA on Windows to remotely debug the openresty lua program on Linux.
Widow on IntelliJ IDEA 2018.2.1+EmmyLua 1.2.6-IDEA182
The program test.lua on Linux has been added:
  local mobdebug = require("src.initial.mobdebug");
  mobdebug.start(8172);

But I don't know Linux is listening to 8172 as a server, and using IDE as a client to connect to Linux port 8172 on Windows? What is the principle? How to use it? Thank you!

**Comment by pkulchenko** [comment]
> Mobdebug.start(8172);

This needs to be `Mobdebug.start("ip-address-of-computer-running-IDE")`; see this section in the documentation for more information: https://studio.zerobrane.com/doc-remote-debugging
