### ISSUE TITLE
mobdebug suddenly gets out of sync

### ISSUE THREAD

**Issue by 1linux** [pkulchenko/MobDebug#47]
In a project (which relies heavily on copas an coroutines) mobdebug suddenly shows these lines, however keeps on working - but verly slow as these lines are repeated permanently.
How can I track down this bug?

INFO		2019-09-13 09:30:40	...Public\Lua\ZeroBraneStudio\lualibs/mobdebug/mobdebug.lua:187: attempt to call field '__tostring' (a nil value)
stack traceback:
	c:\lua\systree\share\lua\5.1\coxpcall.lua:35: in function 'pcall'
	...Public\Lua\ZeroBraneStudio\lualibs/mobdebug/mobdebug.lua:187: in function 'val2str'
	...Public\Lua\ZeroBraneStudio\lualibs/mobdebug/mobdebug.lua:224: in function 'val2str'
	...Public\Lua\ZeroBraneStudio\lualibs/mobdebug/mobdebug.lua:248: in function <...Public\Lua\ZeroBraneStudio\lualibs/mobdebug/mobdebug.lua:147>
INFO		2019-09-13 09:30:40	...Public\Lua\ZeroBraneStudio\lualibs/mobdebug/mobdebug.lua:188: attempt to call field '__serialize' (a nil value)
stack traceback:
	c:\lua\systree\share\lua\5.1\coxpcall.lua:35: in function 'pcall'
	...Public\Lua\ZeroBraneStudio\lualibs/mobdebug/mobdebug.lua:188: in function 'val2str'
	...Public\Lua\ZeroBraneStudio\lualibs/mobdebug/mobdebug.lua:224: in function 'val2str'
	...Public\Lua\ZeroBraneStudio\lualibs/mobdebug/mobdebug.lua:248: in function <...Public\Lua\ZeroBraneStudio\lualibs/mobdebug/mobdebug.lua:147>
Debugging session completed (traced 1 instruction).

**Comment by pkulchenko** [comment]
@1linux, this doesn't look like mobdebug is getting out of sync; this is a case of an error inside `pcall` being reported by your interpreter for some reason. Are you using a custom version of `pcall`? These errors shouldn't be reportable at all.

**Comment by pkulchenko** [comment]
Closing. Please reopen if there is new information on this issue.
