### ISSUE TITLE
the 'debug.traceback' defined in 'local function start(controller_host, controller_port)' has bug

### ISSUE THREAD

**Issue by sonyps5201314** [pkulchenko/MobDebug#54]
the example code from https://github.com/cocos2d/cocos2d-x/blob/v4/cocos/scripting/lua-bindings/script/cocos2d/functions.lua
```lua
function dump(value, description, nesting)
    if type(nesting) ~= "number" then nesting = 3 end

    local lookupTable = {}
    local result = {}

    local traceback = string.split(debug.traceback("", 2), "\n")
    print("dump from: " .. string.trim(traceback[3]))
```
the function call `debug.traceback("", 2),` and assume its result is not null, if use MobDebug remote debugger and open print redirect function like `debugger.redirect='c'` the `dump` function will crash, because the below code:
```lua
    local function f() return function()end end
    if f() ~= f() then -- Lua 5.1 or LuaJIT
      local dtraceback = debug.traceback
      debug.traceback = function (...)
        if select('#', ...) >= 1 then
          local thr, err, lvl = ...
          if type(thr) ~= 'thread' then err, lvl = thr, err end
          local trace = dtraceback(err, (lvl or 1)+1)
          if genv.print == iobase.print then -- no remote redirect
            return trace
          else
            genv.print(trace) -- report the error remotely
            return -- don't report locally to avoid double reporting
          end
        end
``` 
the line `return -- don't report locally to avoid double reporting` return nothing as the result of `debug.traceback,` so I think
we need to change to `return trace` or delete this user implemented `debug.traceback` function

**Comment by pkulchenko** [comment]
[#898](https://github.com/pkulchenko/ZeroBraneStudio/issues/898) provides a workaround for this issue, but I agree that it may need to be removed, as it's not always correct and is not very useful in Lua 5.2+ versions anyway.
