### ISSUE TITLE
I wrote a simple lua file and got an error when debugging

### ISSUE THREAD

**Issue by ZhouJiaZhi** [pkulchenko/MobDebug#57]
Below is the picture of the error
<img width="1041" alt="截屏2020-12-07 22 58 13" src="https://user-images.githubusercontent.com/20750357/101366326-ca6dfb80-38df-11eb-9b6d-639773e70296.png">

**Comment by pkulchenko** [comment]
@ZhouJiaZhi, thank you for the report. Can you add `print(_VERSION, getfenv, setfenv)` as the first line in your script and report back its output?

Also, why do you do require for `src.mobdebug`? It should be `require("mobdebug")`. What version of mobdebug are you using?

**Comment by ZhouJiaZhi** [comment]
Yesterday, the version of my mobdebug was too low. I used the mobdebug-0.51 version installed by luarocks yesterday. I can debug it with version 0.7 today, but I found a strange problem, that is, my breakpoints seem to be unavailable works, now he will stop at a non-breakpoint
<img width="654" alt="截屏2020-12-08 20 38 09" src="https://user-images.githubusercontent.com/20750357/101484900-4b3aff00-3995-11eb-8c56-34eaaf7e796e.png">

**Comment by pkulchenko** [comment]
I'm not sure what environment you use, so it's difficult for me to say what may be going wrong there. I use Mobdebug in the (widely used) ZeroBrane Studio IDE and don't see any issues with misplaced breakpoints. You can run Mobdebug controller from the command line against your script to see what lines are reported for breakpoints.

**Comment by pkulchenko** [comment]
Closing this one, but feel free to re-open if you have any additional information.
