### ISSUE TITLE
Update luarocks please... :)

### ISSUE THREAD

**Issue by andrewstarks** [pkulchenko/MobDebug#58]
The latest LuaRocks version is not compatible with Lua 5.4 and thus breaks when trying to use it with ZBS. Thanks!

**Comment by pkulchenko** [comment]
@andrewstarks, I only put "major" releases in luarocks and 0.70 is the last one registered there. It does support Lua 5.4 (at least according to my tests). Do you have a simple test case that demonstrates that 0.70 doesn't work with Lua 5.4? I do plan to make an upgrade soon, but am still curious about the specific issue with 0.70.
