### ISSUE TITLE
Luasocket bug receive

### ISSUE THREAD

**Issue by cata0309** [pkulchenko/MobDebug#60]
I have the following versions:
luasocket 3.0rc1-2
luasec 1.0.1-1
lua 5.4.3
mobdebug 0.70 from this repository(not from luarocks)

I am trying to debug using Luanalysis from Intellij IDEA
![image](https://user-images.githubusercontent.com/35623921/120111872-4c96f880-c17c-11eb-9061-15680ee43272.png)
![image](https://user-images.githubusercontent.com/35623921/120112007-bfa06f00-c17c-11eb-859c-374ab0c8a989.png)

I get this error message. How could I solve this? I made some research and it might be a luasocket problem or miss use.
http://w3.impa.br/~diego/software/luasocket/tcp.html#receive

**Comment by cata0309** [comment]
The error received is that luasocket 3 receive primitive even if it has a default it must be explicitly passed to the function.
http://w3.impa.br/~diego/software/luasocket/tcp.html#receive
![image](https://user-images.githubusercontent.com/35623921/120116314-47dc3f80-c190-11eb-8152-97a37c125eff.png)
So, what I did is I created a fork of the project and replaced all the
```receive()``` calls with ```receive('*l')```(which is the default)

**Comment by pkulchenko** [comment]
@cata0309, thank you for the report and the patch! I've integrated your changes, but in a slightly different way. Please let me know if you run into any issues with the updated version and Lua 5.4.3
