### ISSUE TITLE
Step in works unstable

### ISSUE THREAD

**Issue by kkolyan** [pkulchenko/MobDebug#62]
Hi!
I'm developing a game on custom engine that run scripts with embedded LuaJIT 2.0.5.

Not too long started to debug scripts with mobdebug and ZBS. For some reason "Step into" feature sometimes doesn't work (it just steps on the next line instead of stepping into a function). But sometimes it works fine. What are the limitations for "Step into"?

**Comment by pkulchenko** [comment]
@kkolyan, you'll need to provide more details about the context when stepping into doesn't work, but I suspect it may be related to the function being defined in a separate file. See this [FAQ answer for additiona details](https://studio.zerobrane.com/doc-faq#why-stepping-into-function-calls-doesnt-work-in-some-cases) and feel free to re-open if it doesn't cover your case.

**Comment by kkolyan** [comment]
Thanks for an answer. Yes, I didn't think about such limitation.
