### ISSUE TITLE
 lua entry thread aborted: runtime error: attempt to yield across C-call boundary

### ISSUE THREAD

**Issue by fairyqb** [pkulchenko/MobDebug#72]
error:

 lua entry thread aborted: runtime error: attempt to yield across C-call boundary

call stack:

/5.1/kong/init.lua: in function 'access'
	access_by_lua(nginx-kong.conf:100):2: in function <access_by_lua(nginx-kong.conf:100):1>, client: 127.0.0.1, server: kong, request: "HEAD / HTTP/1.1", host: "www.test-site.com"

**Comment by pkulchenko** [comment]
Which version of mobdebug and nginx/openresty are you using? This appears to be like the "wrong" coroutine methods are being used. There is a comment/section in mobdebug that describes what may be happening:

```
-- ngx_lua/Openresty requires special handling as its coroutine.*
-- methods use a different mechanism that doesn't allow resume calls
-- from debug hook handlers.
-- Instead, the "original" coroutine.* methods are used.
-- `rawget` needs to be used to protect against `strict` checks
local ngx = rawget(genv, "ngx")
if not ngx then
  -- "older" versions of ngx_lua (0.10.x at least) hide ngx table in metatable,
  -- so need to use that
  local metagindex = getmetatable(genv) and getmetatable(genv).__index
  ngx = type(metagindex) == "table" and metagindex.rawget and metagindex:rawget("ngx") or nil
end
local corocreate = ngx and coroutine._create or coroutine.create
local cororesume = ngx and coroutine._resume or coroutine.resume
local coroyield = ngx and coroutine._yield or coroutine.yield
local corostatus = ngx and coroutine._status or coroutine.status
local corowrap = coroutine.wrap
```

You can add some debugging statements to see if it's being correctly triggered.

**Comment by fairyqb** [comment]
Thank you very much. It's working

**Comment by pkulchenko** [comment]
@fairyqb, just to clarify: did it work for you with the current version or with the proposed patch?
